### ISSUE TITLE
Evaluate script or complex values in domain

### ISSUE THREAD

**Issue by nicholaschiasson** [nicholaschiasson/ngx_upstream_jdomain#51]
Not 100% sure how to accomplish this yet, but the goal would be to be able to do something like the following:

```
upstream test {
    server 127.0.0.1:11111 backup;
    jdomain this-is-${some_variable}-an-example.com;
}
```

This domain name resolution would be guaranteed to fail on load, but I believe it should work at runtime using the context of each request. The reason this becomes unfeasible but not impossible is due to state management. I believe we would need a growable hash of the state object per evaluation of the domain name with its variables.

Some documentation on how to achieve this:

- http://antoine.bonavita.free.fr/nginx_mod_dev_en.html
  - See section 2.7 for info about scripts
- http://nginx.org/en/docs/dev/development_guide.html#http_complex_values

**Comment by atomsnc** [comment]
Hello,

As the nginx dev guide shows the variable being fetched per request, if someone uses a massive map block to set the variable, this could turn out poorly.

I think DNS lookup done at reload/restart time won't really work out to fetch all possible variables values so it would have to be done at runtime.

All first requests to all domain variable values will need to be error handled.

**Comment by nicholaschiasson** [comment]
I will close this as it seems it will have negative performance impact, unfeasible, and for not a lot of gain.
