### ISSUE TITLE
error: missing initializer for field ‘sin_family’ of ‘struct sockaddr_in’

### ISSUE THREAD

**Issue by JamesKenmore** [nicholaschiasson/ngx_upstream_jdomain#73]
I got an error when building and I'm not sure why

	-o objs/addon/src/ngx_http_upstream_jdomain_module.o \
	../ngx_upstream_jdomain/src/ngx_http_upstream_jdomain_module.c
../ngx_upstream_jdomain/src/ngx_http_upstream_jdomain_module.c:110:15: error: missing initializer for field ‘sin_family’ of ‘struct sockaddr_in’ [-Werror=missing-field-initializers]
 static struct sockaddr_in NGX_JDOMAIN_INVALID_ADDR_SOCKADDR_IN = { };
               ^
In file included from /usr/include/bits/socket.h:151:0,
                 from /usr/include/sys/socket.h:39,
                 from src/os/unix/ngx_linux_config.h:44,
                 from src/core/ngx_config.h:26,
                 from ../ngx_upstream_jdomain/src/ngx_http_upstream_jdomain_module.c:2:
/usr/include/netinet/in.h:242:5: note: ‘sin_family’ declared here
     __SOCKADDR_COMMON (sin_);
     ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/src/ngx_http_upstream_jdomain_module.o] Error 1
make[1]: Leaving directory `/root/nginx-1.18.0'
make: *** [build] Error 2

**Comment by splitice** [comment]
Could be your OS? could be old version of GCC?

**Comment by waitspring** [comment]
I have meet this problem too!
My OS is RHEL7, and GCC version is 4.8.5 20150623 (Red Hat 4.8.5-4)

This is my configure command:
```bash
./configure --prefix=/usr/local/nginx \
--sbin-path=/usr/sbin/nginx \
--conf-path=/etc/nginx/nginx.conf \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--user=nginx \
--group=nginx \
--with-debug \
--with-stream \
--with-http_ssl_module \
--with-http_realip_module \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_gzip_static_module \
--with-http_secure_link_module \
--with-http_stub_status_module \
--with-http_gunzip_module \
--with-http_auth_request_module \
--add-module=ngx_upstream_jdomain_1.4.0
```

**Comment by splitice** [comment]
I'm hazarding that version of GCC doesnt have struct initialization?

**Comment by waitspring** [comment]
> I'm hazarding that version of GCC doesnt have struct initialization?

So, can you give us a version requestion of GCC?

**Comment by splitice** [comment]
I suspect GCC 6.1

**Comment by nicholaschiasson** [comment]
@JamesKenmore @waitspring Can we consider this issue closed? Are you able to upgrade your compiler or do you require the module to be built with an older GCC?

**Comment by waitspring** [comment]
> @JamesKenmore @waitspring Can we consider this issue closed? Are you able to upgrade your compiler or do you require the module to be built with an older GCC?

OK, I have solved this problem.
