### ISSUE TITLE
DNS resolution state bug

### ISSUE THREAD

**Issue by atomsnc** [nicholaschiasson/ngx_upstream_jdomain#74]
Hello,

There is a bug in how `resolve.status` is set.

When nginx actually does the lookup, `ngx_http_upstream_jdomain_resolve_handler` is called from polled events which works fine.

But when TTL is set to automatic (no `valid` argument for `resolver` directive) and if it is very high (like 30+ seconds, maybe even less), `ngx_http_upstream_jdomain_resolve_handler` is called from cached values in `ngx_resolve_name_locked` at line **669**.

![Screenshot_20220511_142203](https://user-images.githubusercontent.com/30167941/167950985-ac136653-4071-417d-8b89-1dd28b92120c.png)

As you can see the function stack in bottom left, `ngx_http_upstream_init_jdomain_peer` directly calls `ngx_http_upstream_jdomain_resolve_handler`.

The bug is caused when above happens. As `ngx_http_upstream_jdomain_resolve_handler` sets `NGX_JDOMAIN_STATUS_DONE` for instance resolve status, it returns to  `ngx_http_upstream_init_jdomain_peer` which sets `NGX_JDOMAIN_STATUS_WAIT` as the last step in the loop.

This bug is **irreversible** as once this happens and instance gets set to `NGX_JDOMAIN_STATUS_WAIT`, it never does another lookup again and stays stuck with old peer address.

I think fixing this bug will resolve #60 and #61

**Comment by nicholaschiasson** [comment]
Wow, excellent find, thank you so much! 🙏 I will review the PR and try to have this merged ASAP.

**Comment by splitice** [comment]
@atomsnc Did you get nginx to run in a debugger with build process integration?

Well done! Care to share your setup steps / environment?

**Comment by atomsnc** [comment]
Hello @splitice, I use CLion as it now has Makefile support built-in. You just load Makefile as a project.

https://www.jetbrains.com/help/clion/makefiles-support.html#manual-reload

Since nginx has a pre-make step, you add `./configure` to pre-build command.

Once you build it, you have two options (both require daemon mode to be off), 

- If you disable master process (single nginx process, no worker), you can start a debug build from the start menu. 
- If you want to run with worker process, you will have to start it manually (script works well), and then attach to the process to debug.

Then you can just set breakpoints in IDE window and it works.

You can set access and error logs to /dev/stdout so you have the full experience in the IDE itself.

**Comment by nicholaschiasson** [comment]
Hey @atomsnc , given that #75 is merged, do you suppose we can close this one?

**Comment by atomsnc** [comment]
@nicholaschiasson Yes this can be closed. Please go ahead.
